sui-demo:
#  image: node:8.15.1
  build: .
  volumes:
    - ./pam:/searchui:z
  command: bash -c "tail -f /dev/null"
  environment:
    - ELASTICSEARCH_HOST=http://192.168.0.187:19200
  ports:
    - 3001:3000
